import { ActionButton } from "@/components/action-button";
import { Card, MetricCard, PageHeader, Progress, StatusBadge } from "@/components/ui";
import { applications, infrastructureTargets, teams } from "@/lib/mock-data";
import { aed, percent } from "@/lib/utils";

export default function CostCapacityPage() {
  const spend = applications.reduce((sum, app) => sum + app.spendUsedAed, 0);
  const budget = applications.reduce((sum, app) => sum + app.spendBudgetAed, 0);
  return <div className="page"><PageHeader eyebrow="Optimisation" title="Cost & Capacity" description="Spend forecast, token budgets, GPU allocation, and model graduation opportunities." action={<ActionButton action="Opened cost and capacity planner" target="Cost & Capacity" type="Simulation">Review savings</ActionButton>} /><div className="grid kpis"><MetricCard label="Current spend" value={aed(spend)} detail={`${percent(spend, budget)}% of workspace budgets`} status="Warning" /><MetricCard label="Budget remaining" value={aed(budget - spend)} detail="Across AI Workspaces" status="Healthy" /><MetricCard label="GPU peak" value={`${Math.max(...infrastructureTargets.map((t) => t.gpuLoad))}%`} detail="Claims node pressure" status="Warning" /><MetricCard label="Graduation fit" value="61%" detail="Support traffic can move local" status="Healthy" /></div><div className="grid two" style={{ marginTop: 18 }}><Card pad><h3>Spend by team</h3><div className="mini-bars">{teams.map((team) => <div className="mini-bar" key={team.id}><span>{team.name}</span><Progress value={percent(team.spendUsedAed, team.spendBudgetAed)} /><span>{aed(team.spendUsedAed)}</span></div>)}</div></Card><Card pad><h3>GPU capacity</h3><div className="mini-bars">{infrastructureTargets.filter((target) => target.gpu !== "Not detected").map((target) => <div className="mini-bar" key={target.id}><span>{target.name.replace("Acme ", "").replace(" Node", "")}</span><Progress value={target.gpuLoad} /><span>{target.gpuLoad}%</span></div>)}</div></Card></div><Card pad style={{ marginTop: 18 }}><div className="row"><div><h3>Model graduation candidate</h3><p className="muted">Support Desk AI has repeated Product FAQ traffic. Move repeatable traffic to Falcon Local and semantic cache to reduce external spend.</p></div><StatusBadge value="Healthy" /></div></Card></div>;
}
